spring.application.name=clinic-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/clinicdb
spring.datasource.username=clinic_user
spring.datasource.password=clinic_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true